# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Statement of Purpose'},
        ),
    ]
