# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171125_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
