# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
