# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('knife_type', models.CharField(max_length=255)),
                ('blade_material', models.CharField(max_length=255)),
                ('handle_material', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('blade_length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_source', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('sold_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sold_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Make')),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('flaws', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cap_color', models.CharField(max_length=255)),
                ('body_color', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_source', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('sold_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Make')),
                ('nib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Nib')),
            ],
        ),
        migrations.AddField(
            model_name='knife',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Make'),
        ),
    ]
