# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nib',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='knife',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pen',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
    ]
