# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_pen_nib_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('P', 'Pending'), ('O', 'On Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pen',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('P', 'Pending'), ('O', 'On Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
    ]
