# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-08 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170708_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='appt',
            new_name='apt',
        ),
    ]
