# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:54
from __future__ import unicode_literals

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170708_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pen',
            name='year',
            field=models.IntegerField(validators=[apps.shop.models.validate_year]),
        ),
    ]
