# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 04:31
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
