# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20161216_0431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Test',
        ),
    ]
