# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170929_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('length', models.DecimalField(decimal_places=1, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='knife',
            name='item_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knife', to='shop.ItemDetail'),
        ),
        migrations.AddField(
            model_name='pen',
            name='item_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pen', to='shop.ItemDetail'),
        ),
    ]
