# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20161216_0432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Content',
        ),
    ]
