# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170929_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knife',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='item_details',
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_detail', to='shop.Pen'),
        ),
    ]
