# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0009_auto_20170929_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
