# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
