# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.CharField(max_length=2000),
        ),
    ]
