# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170930_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
