# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170930_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='content_type',
        ),
        migrations.AddField(
            model_name='knife',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=4.4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knife',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=226.8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knife',
            name='width',
            field=models.DecimalField(decimal_places=1, default=13.8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pen',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=4.4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pen',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=226.8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pen',
            name='width',
            field=models.DecimalField(decimal_places=1, default=13.8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knife',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pen',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.DeleteModel(
            name='ItemDetail',
        ),
    ]
