# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170930_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knife',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='width',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='width',
        ),
        migrations.AddField(
            model_name='knife',
            name='packing_depth',
            field=models.DecimalField(decimal_places=1, default=4.4, max_digits=5),
        ),
        migrations.AddField(
            model_name='knife',
            name='packing_length',
            field=models.DecimalField(decimal_places=1, default=22.1, max_digits=5),
        ),
        migrations.AddField(
            model_name='knife',
            name='packing_weight',
            field=models.DecimalField(decimal_places=1, default=226.8, max_digits=5),
        ),
        migrations.AddField(
            model_name='knife',
            name='packing_width',
            field=models.DecimalField(decimal_places=1, default=13.7, max_digits=5),
        ),
        migrations.AddField(
            model_name='pen',
            name='packing_depth',
            field=models.DecimalField(decimal_places=1, default=4.4, max_digits=5),
        ),
        migrations.AddField(
            model_name='pen',
            name='packing_length',
            field=models.DecimalField(decimal_places=1, default=22.1, max_digits=5),
        ),
        migrations.AddField(
            model_name='pen',
            name='packing_weight',
            field=models.DecimalField(decimal_places=1, default=226.8, max_digits=5),
        ),
        migrations.AddField(
            model_name='pen',
            name='packing_width',
            field=models.DecimalField(decimal_places=1, default=13.7, max_digits=5),
        ),
        migrations.AlterField(
            model_name='knife',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pen',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
