# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170203_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pen',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
