# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170214_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=155)),
                ('text', models.TextField(max_length=2000)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AlterField(
            model_name='knife',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knife', to='shop.Make'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('O', 'On Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='nib',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('O', 'On Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pen',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen', to='shop.Make'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen', to='shop.Nib'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('O', 'On Sale'), ('C', 'Collection')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='knife',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knife', to='shop.Sale'),
        ),
        migrations.AddField(
            model_name='pen',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pen', to='shop.Sale'),
        ),
    ]
