# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170930_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='knife',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knife', to='shop.Order'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pen', to='shop.Order'),
        ),
    ]
