# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170930_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('condition', models.CharField(choices=[('mint', 'mint'), ('near_mint', 'near mint'), ('excellent_plus', 'excellent +'), ('excellent', 'excellent'), ('very_good_plus', 'very good +'), ('very_good', 'very good'), ('good', 'good'), ('fair', 'fair'), ('poor', 'poor')], max_length=25)),
                ('flaws', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('S', 'Sold'), ('A', 'For Sale'), ('P', 'Pending'), ('O', 'On Sale'), ('C', 'Collection')], default='A', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_source', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('description', models.TextField(max_length=2000)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=1, default=226.8, max_digits=5)),
                ('length', models.DecimalField(decimal_places=1, default=22.1, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, default=13.7, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=1, default=4.4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Order')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Sale')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='description',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='length',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='make',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='model',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='order',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='packing_depth',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='packing_length',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='packing_weight',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='packing_width',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='price',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='purchase_source',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='status',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='knife',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='flaws',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='length',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='make',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='model',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='packing_depth',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='packing_length',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='packing_weight',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='packing_width',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='purchase_source',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='knife',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='knife', to='shop.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pen',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pen', to='shop.Product'),
            preserve_default=False,
        ),
    ]
