# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20171001_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=85, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
