# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20171001_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='blade_material',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='knife',
            name='handle_material',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='knife',
            name='knife_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='body_color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='cap_color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_description',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_flexibility',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_grade',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_make',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_material',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_style',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='flaws',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_source',
            field=models.CharField(max_length=55),
        ),
    ]
