# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20171001_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
