# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:23
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20171020_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+15107543279', max_length=128),
            preserve_default=False,
        ),
    ]
