# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20171105_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='apropas@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
