# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.Address'),
            preserve_default=False,
        ),
    ]
