# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20171113_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('card', 'Credit Card')], default='paypal', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed')], max_length=1),
        ),
    ]
