# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20171119_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='nib_style',
        ),
    ]
