# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_pen_nib_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed')], max_length=10),
        ),
    ]
