# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20171125_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Order'),
        ),
    ]
