# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20171210_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
