# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 06:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20171226_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ManyToManyField(related_name='image', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='If number in stock is more than 1 enter average purchase cost', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=1, help_text='If number is 0 product must be marked sold.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
