# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-29 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20181229_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('headline', models.CharField(default='The Penguin is on vacation!', max_length=155)),
                ('message', models.TextField(default='We will be back and will resume shipping on ', max_length=75000)),
                ('end_date', models.DateField(default=datetime.date(2018, 12, 29))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vacation Settings',
                'verbose_name_plural': 'Vacation Settings',
            },
        ),
        migrations.DeleteModel(
            name='VacationMode',
        ),
    ]
