# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20200316_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(choices=[('usps', 'USPS'), ('fedex', 'FedEx')], max_length=25),
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='carrier',
            field=models.TextField(choices=[('usps', 'USPS'), ('fedex', 'FedEx')]),
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='locale',
            field=models.TextField(choices=[('US', 'United States of America'), ('CA', 'Canada'), ('INTER', 'International')]),
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='order_size_cat',
            field=models.TextField(choices=[('lte5', '5 or fewer'), ('gt5', 'more than 5')]),
        ),
    ]
