# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-08 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20200526_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('express', 'Express')], max_length=55),
        ),
    ]
