# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-10 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20200609_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingoptions',
            options={'verbose_name': 'Shipping Options', 'verbose_name_plural': 'Shipping Options'},
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='carrier',
            field=models.CharField(choices=[('usps', 'USPS'), ('fedex', 'FedEx')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='locale',
            field=models.CharField(choices=[('US', 'United States of America'), ('CA', 'Canada'), ('INTER', 'International')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='order_size_cat',
            field=models.CharField(choices=[('lte5', '5 or fewer'), ('gt5', 'more than 5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingoptions',
            name='service_type',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('express', 'Express')], max_length=255),
        ),
    ]
